apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: capi-profiles
  namespace: flux-system
spec:
  interval: 2m0s
  path: ./weave-gitops-platform/capi-profiles
  prune: true
  wait: true
  timeout: 5m
  sourceRef:
    kind: GitRepository
    name: flux-system